services:
  scheduler:
    image: rides-bot:latest
    container_name: rides-bot-scheduler
    volumes:
      - ./config.yaml:/rides-bot/src/config.yaml
    environment:
      - RIDESBOT_SCHEDULER_RUN_AT=0 7 * * *
      - RIDESBOT_SCHEDULER_RUN_COMMAND=python3 -m rides_bot.app -ag9tn
    networks:
      - default
  groupme:
    image: rides-bot:latest
    container_name: rides-bot-groupme
    command:
      - listener
      - groupme
    volumes:
      - ./config.yaml:/rides-bot/src/config.yaml
    networks:
      - caddy
      - default
    labels:
      caddy: callbacks.ridesdepartment.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.reverse_proxy.import: error-pages
  telegram:
    image: rides-bot:latest
    container_name: rides-bot-telegram
    command:
      - listener
      - telegram
    volumes:
      - ./config.yaml:/rides-bot/src/config.yaml
    networks:
      - default
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: rides-bot-status
    restart: unless-stopped
    depends_on:
      - scheduler
      - groupme
      - telegram
    volumes:
      - /opt/docker/data/rides-bot/uptime-kuma:/app/data
    networks:
      - caddy
      - default
    labels:
      caddy_0: botstatus.ridesdepartment.com
      caddy_0.reverse_proxy: "{{upstreams 3001}}"
      caddy_0.reverse_proxy.import: error-pages
      caddy_1: ridesbot.ridesdepartment.com
      caddy_1.reverse_proxy:  "{{upstreams 3001}}"
      caddy_1.reverse_proxy.import: error-pages
networks:
  caddy:
    external: true
